### ISSUE TITLE
Running Tests written in Typescript

### ISSUE THREAD

**Issue by DavidRogersDev** [marcol/vue-cli-plugin-e2e-playwright#26]
I have an application written in Typescript. I'd like to also write tests in Typescript. Playwright, Mocha and Chai all support Typescript, but I cannot figure out how to structure the code. I keep getting errors such as `SyntaxError: Cannot use import statement outside a module`.

I've come up with something like this, but I suspect the Typescript compiler does not like having method invocations outside of a class:    

```import { chromium, Browser, Page } from "playwright";
import { expect } from "chai";
import { describe } from "mocha";


describe("My example E2E test with Playwright", () => {
  let browser!: Browser;
  let page!: Page;

  before(async () => {
    browser = await chromium.launch();
    page = await browser.newPage();
    await page.goto("https://www.example.com/");
  });

  after(async () => {
    await page.close();
    await browser.close();
  });

  it("has header", async () => {
    const h1 = await page.$("h1");
    const text = await h1?.innerText();
    expect(text).to.equal("Example Domain");
  });
});
```

If this is something you know how to structure, would you please be able to add a snippet in the doco for this project. That would be most appreciated.

If not, no problems.

Thanks

**Comment by marcol** [comment]
Hi. I'm not very proficient with Typescript. Can you please the module type in your `tsconfig.json`. I believe it should be with `es2015`. If you are not able to do that, try with `require` instead of import.

**Comment by DavidRogersDev** [comment]
Unfortunately, that did not work.
That's OK. I can get it working with the tests written in normal Javascript.

I think I can go with that. Cheers.
