### ISSUE TITLE
using ES2020

### ISSUE THREAD

**Issue by DimaYnkv** [marcol/vue-cli-plugin-e2e-playwright#29]
Hi, we are having issue using es2020 operator chaining with your plugin -
we are getting this error:
You may need an additional loader to handle the result of these loaders.

`You may need an additional loader to handle the result of these loaders.
|
|     isParamLocked() {
>       return this.getUpdatedLocks?.lockCollisions?.get(this.paramName);
|     }`

Is there any setting we can change to make it work?

**Comment by marcol** [comment]
Not sure if this is a problem with the plugin. It seems that `this` might not be what you are expecting.
